# Generated by Django 4.2.10 on 2024-02-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=5)),
                ('full_name', models.CharField(max_length=255)),
                ('credit', models.SmallIntegerField()),
                ('section', models.CharField(max_length=6)),
                ('class_day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
                ('class_start', models.TimeField()),
                ('class_finish', models.TimeField()),
            ],
        ),
    ]
