# Generated by Django 4.2.10 on 2024-02-15 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_course_class_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='room',
            field=models.CharField(default='exit', max_length=10),
            preserve_default=False,
        ),
    ]
