# Generated by Django 4.2.10 on 2024-02-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorm', '0002_remove_room_members_bill_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
