# Generated by Django 4.2.10 on 2024-02-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dorm', '0003_alter_bill_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='payment_status',
        ),
    ]
