# Generated by Django 4.2.10 on 2024-02-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorm', '0004_remove_bill_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
