# Generated by Django 4.2.10 on 2024-02-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dorm', '0005_bill_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='rental_cost',
            field=models.FloatField(default=0.0),
        ),
    ]
