# Generated by Django 4.2.10 on 2024-02-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0002_alter_course_class_day'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_courses',
            field=models.ManyToManyField(to='Course.course'),
        ),
    ]
