# Generated by Django 4.2.10 on 2024-02-15 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_student_enrolled_courses_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='faculty',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
