# Generated by Django 4.2.10 on 2024-02-15 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_student_department_student_faculty'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='0963163858', max_length=12),
            preserve_default=False,
        ),
    ]
