# Generated by Django 4.2.10 on 2024-02-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_student_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='room',
        ),
    ]
