# Generated by Django 4.2.10 on 2024-02-20 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Dorm', '0005_bill_payment_status'),
        ('User', '0013_student_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Dorm.room'),
        ),
    ]
